---
# Visit https://github.com/lowlighter/metrics/blob/master/action.yml 
name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          output_action: commit
          # Config
          user: qboileau
          template: classic
          config_gemoji: yes
          config_timezone: Europe/Paris
          retries: 3
          retries_delay: 300
          use_prebuilt_image: yes

          # base
          base: header, activity, community, repositories, metadata
          repositories_forks: no
          repositories_affiliations: owner, collaborator
          repositories_skipped: qboileau/qboileau

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          debug: yes
          debug_print: yes
          plugin_languages: yes # disable temporary not working error : "TypeError: Cannot destructure property 'committer' of 'undefined' as it is undefined."
          #plugin_languages_ignored: 
          plugin_languages_details: bytes-size, percentage
          plugin_languages_sections: most-used, recently-used

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 90
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_stars: yes
          plugin_stars_limit: 4

          plugin_reactions: yes
          plugin_reactions_limit: 200
          plugin_reactions_days: 90
          plugin_reactions_details: count

          plugin_followup: yes
          plugin_followup_sections: repositories, user

          plugin_lines: yes

          plugin_traffic: yes

          plugin_stargazers: yes

          plugin_notable: yes
          plugin_notable_filter: stars:>20
          plugin_notable_repositories: no
